name: windows

on:
  push:
    branches: [ '**' ]
    tags:
      - V**
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  windows_mingw:
    runs-on: windows-2022

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-qt6-base
            mingw-w64-x86_64-qt6-multimedia

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        run: ctest --test-dir build --output-on-failure

  windows_msvc:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          arch: 'win64_msvc2022_64'
          version: '6.8.3'
          modules: 'qtmultimedia'
          aqtversion: '==3.1.7'

      - name: Configure
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Test
        run: ctest --test-dir build --output-on-failure -C Release
